### ISSUE TITLE
Folder already exist error

### ISSUE THREAD

**Issue by akshatg** [sundevista/youtube-template#30]
Keep getting this error after the first video note is created and an attachment folder gets created in main directory.
If I delete the attachment folder from main directory it works again and again create the folder but then again it doesnt work.
I have tried different settings in the option but non worked.

Used create folder on and off also nothing helped.

**Comment by zenseeker0** [comment]
**Issue**: After the first use, the next attempts generate "Error: Folder already exists."
**Workaround**: Change Obsidian's default location for attachments to the "attachments" folder the plug-in used (or created) in the vault folder.

**Console output in debug mode**:
```
plugin:youtube-template:352 Error: Folder already exists.
    at t.<anonymous> (app.js:1:733572)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051) 'Folder already exists.'
InsertTemplateModal.onSubmitClick @ plugin:youtube-template:352
await in InsertTemplateModal.onSubmitClick (async)
InsertTemplateModal.onEnterKeyPressing @ plugin:youtube-template:374
```

**Comment by zenseeker0** [comment]
**Workaround #2:** Do not use {{thumbnail}} in templates. Using {{thumbnail}} downloads the thumbnail image to attachments. Without {{thumbnail}} the extension doesn't download an image attachment and it seems to be okay with whichever attachment location is set in Obsidian preferences after some testing.

**Comment by sundevista** [comment]
@zenseeker0 @akshatg This week I'll fix a bunch of issues for the plugin, I'll let you know when this one is done

**Comment by sundevista** [comment]
@zenseeker0 @akshatg Hi! I've tried to reproduce the issue but it's working on my side. Can you create a separated vault with the latest version (1.1.10) of the plugin and send it here as zip, so I can reproduce and fix that?

**Comment by sundevista** [comment]
A new update (1.2.1) should also should cover some edge cases with "Allow duplicates" setting.

I'll close the issue for now, if you experience this issue with the latest update, feel free to reopen
